"""SIGIL4CPython experimental typed contracts.

The package is intentionally pure Python and dependency-free. It carries
SIGIL/UAP/KQC guardrail metadata without changing CPython interpreter semantics.
Optional Pydantika and DisCoPy projections live under ``Tools/sigil4cpython``.
"""

from .kqc_sheaf import (
    CompilerKernel,
    CompilerStrategy,
    HarmonicConstraint,
    KQCKernelType,
    KQCPublicationSheaf,
    MeasurementProfile,
    PublicationAuthority,
    PublicationHop,
    PullbackWitness,
    RelationKind,
    RepositorySection,
    TQFTCoherenceProfile,
    ThirdWheelFactor,
    TypedRelation,
    UAPState,
    compile_publication_sheaf,
)
from .pydantika_coherent_projection import (
    AUTHOR as PYDANTIKA_COHERENT_AUTHOR,
    SCHEMA_ID as PYDANTIKA_COHERENT_SCHEMA_ID,
    SEMANTIC_KERNEL_ID as PYDANTIKA_SEMANTIC_KERNEL_ID,
    SOURCE_BRANCH as PYDANTIKA_COHERENT_SOURCE_BRANCH,
    SOURCE_REPOSITORY as PYDANTIKA_COHERENT_SOURCE_REPOSITORY,
    SOURCE_SHA as PYDANTIKA_COHERENT_SOURCE_SHA,
    AnnotatedKernelSection,
    AnnotatedRestriction,
    PydantikaCoherentProjection,
    VoidOuroborosProjection,
    build_pydantika_coherent_projection,
    compile_pydantika_coherent_projection,
)
from .pacacore_standard_model_projection import (
    BACKENDS as PACACORE_STANDARD_MODEL_BACKENDS,
    FACETS as PACACORE_STANDARD_MODEL_FACETS,
    SCHEMA_ID as PACACORE_STANDARD_MODEL_SCHEMA_ID,
    SOURCE_BUNDLE_SHA256 as PACACORE_STANDARD_MODEL_SOURCE_BUNDLE_SHA256,
    SOURCE_PULL_REQUEST as PACACORE_STANDARD_MODEL_SOURCE_PULL_REQUEST,
    SOURCE_REPLAY_TIP as PACACORE_STANDARD_MODEL_SOURCE_REPLAY_TIP,
    SOURCE_REPOSITORY as PACACORE_STANDARD_MODEL_SOURCE_REPOSITORY,
    SOURCE_SCHEMA as PACACORE_STANDARD_MODEL_SOURCE_SCHEMA,
    SOURCE_SHA as PACACORE_STANDARD_MODEL_SOURCE_SHA,
    PACACoreStandardModelProjection,
    build_pacacore_standard_model_projection,
    validate_pacacore_standard_model_projection,
)
from .uap_wards import (
    DEFAULT_CLAIM_BOUNDARY,
    KokompiledKernel,
    UAPWard,
    UAPWardVerdict,
    build_pacadocencia_uap_kernel,
    check_uap_wards,
    kokompile_kernel,
    validate_kokompiled_kernel,
)
from .vortice_twerk_sheaf import (
    AUTHOR as VORTICE_TWERK_AUTHOR,
    SCHEMA_ID as VORTICE_TWERK_SHEAF_SCHEMA_ID,
    SOURCE_BRANCH as VORTICE_TWERK_SOURCE_BRANCH,
    SOURCE_REPOSITORY as VORTICE_TWERK_SOURCE_REPOSITORY,
    SOURCE_SHA as VORTICE_TWERK_SOURCE_SHA,
    CoherentProjection,
    ProjectionVerdict,
    RestrictionWitness,
    SheafSection,
    build_projection as build_vortice_twerk_projection,
    compile_projection as compile_vortice_twerk_projection,
)

__all__ = [
    "AnnotatedKernelSection",
    "AnnotatedRestriction",
    "CompilerKernel",
    "CompilerStrategy",
    "DEFAULT_CLAIM_BOUNDARY",
    "HarmonicConstraint",
    "KQCKernelType",
    "KQCPublicationSheaf",
    "KokompiledKernel",
    "MeasurementProfile",
    "PACACORE_STANDARD_MODEL_BACKENDS",
    "PACACORE_STANDARD_MODEL_FACETS",
    "PACACORE_STANDARD_MODEL_SCHEMA_ID",
    "PACACORE_STANDARD_MODEL_SOURCE_BUNDLE_SHA256",
    "PACACORE_STANDARD_MODEL_SOURCE_PULL_REQUEST",
    "PACACORE_STANDARD_MODEL_SOURCE_REPLAY_TIP",
    "PACACORE_STANDARD_MODEL_SOURCE_REPOSITORY",
    "PACACORE_STANDARD_MODEL_SOURCE_SCHEMA",
    "PACACORE_STANDARD_MODEL_SOURCE_SHA",
    "PACACoreStandardModelProjection",
    "PYDANTIKA_COHERENT_AUTHOR",
    "PYDANTIKA_COHERENT_SCHEMA_ID",
    "PYDANTIKA_COHERENT_SOURCE_BRANCH",
    "PYDANTIKA_COHERENT_SOURCE_REPOSITORY",
    "PYDANTIKA_COHERENT_SOURCE_SHA",
    "PYDANTIKA_SEMANTIC_KERNEL_ID",
    "PublicationAuthority",
    "PublicationHop",
    "PullbackWitness",
    "PydantikaCoherentProjection",
    "RelationKind",
    "RepositorySection",
    "TQFTCoherenceProfile",
    "ThirdWheelFactor",
    "TypedRelation",
    "UAPState",
    "UAPWard",
    "UAPWardVerdict",
    "VoidOuroborosProjection",
    "build_pacadocencia_uap_kernel",
    "build_pacacore_standard_model_projection",
    "build_pydantika_coherent_projection",
    "check_uap_wards",
    "compile_publication_sheaf",
    "compile_pydantika_coherent_projection",
    "kokompile_kernel",
    "validate_kokompiled_kernel",
    "validate_pacacore_standard_model_projection",
    "CoherentProjection",
    "ProjectionVerdict",
    "RestrictionWitness",
    "SheafSection",
    "VORTICE_TWERK_AUTHOR",
    "VORTICE_TWERK_SHEAF_SCHEMA_ID",
    "VORTICE_TWERK_SOURCE_BRANCH",
    "VORTICE_TWERK_SOURCE_REPOSITORY",
    "VORTICE_TWERK_SOURCE_SHA",
    "build_vortice_twerk_projection",
    "compile_vortice_twerk_projection",
]
